/**
 * Listing galleries are generated by `npm run images` from the raw folders in
 * src/assets/images/Aangan Realty/. `count` must match what the script wrote —
 * `npm test` fails if a listing points at a file that does not exist.
 */
const gallery = (slug: string, count: number) =>
  Array.from(
    { length: count },
    (_, i) =>
      new URL(
        `../assets/properties/${slug}/${String(i + 1).padStart(2, '0')}.webp`,
        import.meta.url,
      ).href,
  )

/** 1 var (sq. yard) = 9 sq.ft. — Gujarat plots and bungalows are quoted in var. */
const VAR = 9

export const PROPERTY_TYPES = [
  'Apartment',
  'Bungalow',
  'Tenement',
  'Studio',
] as const

export const STATUSES = ['For Sale', 'For Rent', 'New Launch'] as const

export type PropertyType = (typeof PROPERTY_TYPES)[number]
export type Status = (typeof STATUSES)[number]

export type Property = {
  id: string
  slug: string
  title: string
  locality: string
  city: string
  /** absolute rupees — kept numeric so filtering and sorting stay honest. 0 = price on request */
  price: number
  /** true when `price` is the entry point of a project, not a single unit */
  priceFrom?: boolean
  /** monthly rupees for rentals, otherwise null */
  rent: number | null
  type: PropertyType
  status: Status
  beds: number
  /** 0 = not stated */
  baths: number
  /** sq.ft. as quoted (carpet, built-up or SBA — the highlights say which). 0 = on request */
  area: number
  facing: string
  furnishing: string
  floor: string
  parking: number
  possession: string
  featured: boolean
  summary: string
  description: string[]
  highlights: string[]
  amenities: string[]
  images: string[]
}

const ON_REQUEST = 'On request'

export const properties: Property[] = [
  {
    id: 'p1',
    slug: '5bhk-tenement-naranpura',
    title: '5BHK Residential Tenement, Naranpura',
    locality: 'Naranpura',
    city: 'Ahmedabad',
    price: 35000000,
    rent: null,
    type: 'Tenement',
    status: 'For Sale',
    beds: 5,
    baths: 0,
    area: 280 * VAR,
    facing: ON_REQUEST,
    furnishing: ON_REQUEST,
    floor: 'Independent house',
    parking: 0,
    possession: ON_REQUEST,
    featured: true,
    summary:
      'A spacious 5BHK tenement on a 320 var plot, with a large front open space and a huge private terrace.',
    description: [
      'A well-planned 5BHK tenement in one of Ahmedabad’s most sought-after residential pockets — generous living spaces, a large plot, a private terrace and ample open areas for comfortable family living.',
      'The plot is 320 var with 280 var of construction. A wide front open space takes parking and gardening, a rear open area works for utility, and the terrace is large enough for evenings and family gatherings.',
      'Behind Indian Bank, near Vijay Nagar Cross Road, Ankur, Naranpura — 380013. Equally a family home or a long-term investment.',
    ],
    highlights: [
      '320 var plot, 280 var (≈2,520 sq.ft.) construction',
      'Large front open space with ample parking',
      'Huge private terrace',
      'Close to Vijay Nagar Cross Road and Indian Bank',
    ],
    amenities: [
      'Private terrace',
      'Front open space',
      'Rear open space',
      'Ample parking',
      'Side utility area',
      'Prime residential location',
    ],
    images: gallery('5bhk-tenement-naranpura', 15),
  },
  {
    id: 'p2',
    slug: 'sky-97-shela',
    title: 'Sky 97 by Prarambh Group',
    locality: 'Shela',
    city: 'Ahmedabad',
    price: 1950 * 3500,
    priceFrom: true,
    rent: null,
    type: 'Apartment',
    status: 'For Sale',
    beds: 3,
    baths: 0,
    area: 1950,
    facing: ON_REQUEST,
    furnishing: ON_REQUEST,
    floor: '5 individual towers',
    parking: 0,
    possession: ON_REQUEST,
    featured: true,
    summary:
      'Premium 3 & 4 BHK residences on the 36 m VIP Road at Shela — five individual towers with landscaped open space.',
    description: [
      'Sky 97 by Prarambh Group is a set of premium 3 and 4 BHK residences at Shela, designed for spacious living, natural light and ventilation, with modern lifestyle amenities and premium commercial spaces on the lower floors.',
      'Apartment options: 3 BHK of 1,950 sq.ft. (SBA) and 4 BHK of 4,000 sq.ft. (SBA). The project has five individual towers on the 36-metre VIP Road, opposite Kavisha Amara.',
      'Rates per sq.ft. (SBA): ₹3,500 on a down-payment plan, ₹3,900 semi down-payment, ₹4,400 regular. The price shown is a 3 BHK on the down-payment rate.',
    ],
    highlights: [
      '3 BHK 1,950 sq.ft. · 4 BHK 4,000 sq.ft. (SBA)',
      '₹3,500 / ₹3,900 / ₹4,400 per sq.ft. — DP / semi-DP / regular',
      'Five individual towers on the 36 m VIP Road',
      'Opposite Kavisha Amara, Shela',
    ],
    amenities: [
      'Landscaped open spaces',
      'Modern lifestyle amenities',
      'Indoor games',
      'Gymnasium',
      'Kids play area',
      'Commercial spaces',
    ],
    images: gallery('sky-97-shela', 8),
  },
  {
    id: 'p3',
    slug: '3bhk-bungalow-nikol',
    title: '3BHK Fully Furnished Bungalow, Nikol',
    locality: 'Nikol',
    city: 'Ahmedabad',
    price: 17000000,
    rent: null,
    type: 'Bungalow',
    status: 'For Sale',
    beds: 3,
    baths: 0,
    area: 190 * VAR,
    facing: ON_REQUEST,
    furnishing: 'Fully furnished',
    floor: 'Independent house',
    parking: 0,
    possession: 'Ready to move',
    featured: true,
    summary:
      'A ready-to-move, fully furnished 3BHK bungalow in Aastha Bungalows, near Nikol D-Mart.',
    description: [
      'A premium 3BHK bungalow sold fully furnished and ready to move into, in Aastha Bungalows near Nikol D-Mart.',
      'The plot is 120 var with 190 var of construction. It is a prime residential location with excellent connectivity and all daily essentials close by.',
    ],
    highlights: [
      '120 var plot, 190 var (≈1,710 sq.ft.) construction',
      'Fully furnished, ready to move',
      'Aastha Bungalows, near Nikol D-Mart',
      'Daily essentials within easy reach',
    ],
    amenities: [
      'Fully furnished',
      'Modular kitchen',
      'Gated society',
      'Terrace',
      'Balcony',
      'Near D-Mart',
    ],
    images: gallery('3bhk-bungalow-nikol', 7),
  },
  {
    id: 'p4',
    slug: '3bhk-corner-bungalow-vastral',
    title: '3BHK Corner Bungalow, Vastral',
    locality: 'Vastral',
    city: 'Ahmedabad',
    price: 12000000,
    rent: null,
    type: 'Bungalow',
    status: 'For Sale',
    beds: 3,
    baths: 0,
    area: 0,
    facing: 'Corner plot',
    furnishing: 'Semi-furnished',
    floor: 'Independent house',
    parking: 0,
    possession: 'Ready to move',
    featured: true,
    summary:
      'A semi-furnished corner bungalow off Vastral RTO Road, with extra open space and the metro station at walking distance.',
    description: [
      'A semi-furnished corner bungalow that blends comfort, convenience and modern living — a sound choice whether you are buying your first home or upgrading.',
      'Three bedrooms, two spacious halls, a modular kitchen with separate dining space, a temple area, and a balcony with a big agashi. The house is well ventilated, and being a corner property it carries extra open space.',
      'In Ajay-5, off Vastral RTO Road, in a peaceful, family-friendly locality with the metro station at walking distance.',
    ],
    highlights: [
      'Corner bungalow with extra open space',
      '3 bedrooms and 2 spacious halls',
      'Balcony and a big agashi',
      'Metro station at walking distance',
    ],
    amenities: [
      'Modular kitchen',
      'Separate dining space',
      'Temple area',
      'Balcony',
      'Agashi (terrace)',
      'Semi-furnished',
      'Well ventilated',
      'Near metro station',
    ],
    images: gallery('3bhk-corner-bungalow-vastral', 18),
  },
  {
    id: 'p5',
    slug: 'happy-aura-ghuma',
    title: 'Happy Aura',
    locality: 'South Bopal Extension, Ghuma',
    city: 'Ahmedabad',
    price: 9000000,
    priceFrom: true,
    rent: null,
    type: 'Apartment',
    status: 'New Launch',
    beds: 3,
    baths: 0,
    area: 1850,
    facing: ON_REQUEST,
    furnishing: ON_REQUEST,
    floor: '10-storey towers',
    parking: 1,
    possession: 'December 2026 (per developer)',
    featured: true,
    summary:
      'Spacious 3 & 4 BHK residences on a 2-road corner in South Bopal Extension — a pure residential community by Happy Group.',
    description: [
      'Happy Aura is where contemporary architecture meets peaceful living in South Bopal Extension, Ghuma. Every home is planned with spacious layouts, abundant natural light and thoughtfully planned amenities.',
      'Configurations are 3 BHK of 1,850 sq.ft. and 4 BHK of 3,700 sq.ft., across four 10-storey towers with two lifts in each block and one allotted car park per home.',
      'It is a pure residential community on a prime 2-road corner location, with no commercial units on site.',
    ],
    highlights: [
      '3 BHK 1,850 sq.ft. · 4 BHK 3,700 sq.ft.',
      'Prime 2-road corner location',
      'Pure residential community',
      'Dedicated car parking for every home',
    ],
    amenities: [
      'Library',
      'Home theatre',
      'Gymnasium',
      'Indoor games',
      'Splash pool',
      'Multipurpose hall',
      'Temple',
      'Landscaped spaces',
    ],
    images: gallery('happy-aura-ghuma', 9),
  },
  {
    id: 'p6',
    slug: 'happy-uptown-shela',
    title: 'Happy Uptown',
    locality: 'VIP Road, Shela',
    city: 'Ahmedabad',
    price: 6400000,
    priceFrom: true,
    rent: null,
    type: 'Apartment',
    status: 'For Sale',
    beds: 2,
    baths: 0,
    area: 1260,
    facing: ON_REQUEST,
    furnishing: ON_REQUEST,
    floor: ON_REQUEST,
    parking: 0,
    possession: ON_REQUEST,
    featured: true,
    summary:
      '2 BHK homes of 1,260–1,300 sq.ft. on VIP Road, Shela — with a balcony made for slow mornings. Only a few units left.',
    description: [
      'Happy Uptown is designed for calm mornings, beautiful views and pure comfort: 2 BHK homes with 1,260–1,300 sq.ft. of spacious living.',
      'Every home has a balcony made for slow mornings and sunset evenings. The project is on VIP Road, Shela, and only a few units remain.',
    ],
    highlights: [
      '2 BHK, 1,260–1,300 sq.ft.',
      'Balcony with every home',
      'VIP Road, Shela',
      'Only a few units remaining',
    ],
    amenities: [
      'Library',
      'Party lawn & common garden',
      'Day care / toddlers’ area',
      'Music & dance studio',
      'Multipurpose hall',
      'Splash pool',
      'Indoor game room',
      'Senior citizen sitting',
      'Shiv temple',
      'Gazebo',
      'Gymnasium',
      'Children’s play area',
    ],
    images: gallery('happy-uptown-shela', 11),
  },
  {
    id: 'p7',
    slug: 'happy-habitat-shela',
    title: 'Happy Habitat',
    locality: 'Shela',
    city: 'Ahmedabad',
    price: 3600000,
    priceFrom: true,
    rent: null,
    type: 'Apartment',
    status: 'New Launch',
    beds: 1,
    baths: 0,
    area: 750,
    facing: ON_REQUEST,
    furnishing: ON_REQUEST,
    floor: '14-storey towers',
    parking: 0,
    possession: ON_REQUEST,
    featured: false,
    summary:
      'Luxury 1 BHK apartments of 750 sq.ft. with commercial shops, in one master-planned Happy Group community at Shela.',
    description: [
      'Happy Habitat by Happy Group blends luxury 1 BHK apartments and prime commercial shops under one master plan — a genuinely all-in-one community.',
      'Five 14-storey towers hold 760 units, with 37 commercial shops on the ground and first floors. Apartments are 1 BHK at 750 sq.ft.',
      'Garden, play area, jogging track and a party lawn are part of the plan. Suits both a first home and a rental investment.',
    ],
    highlights: [
      'Luxury 1 BHK at 750 sq.ft.',
      '5 towers · 14 storeys · 760 units',
      '37 commercial shops on ground and first floor',
      'Garden, jogging track and party lawn',
    ],
    amenities: [
      'Garden',
      'Play area',
      'Jogging track',
      'Party lawn',
      'Commercial shops',
    ],
    images: gallery('happy-habitat-shela', 7),
  },
  {
    id: 'p8',
    slug: '9-percent-club-studios-shela',
    title: 'Codename 9% Club — Studio Apartments',
    locality: 'Club 07, Shela',
    city: 'Ahmedabad',
    price: 2300000,
    priceFrom: true,
    rent: null,
    type: 'Studio',
    status: 'New Launch',
    beds: 0,
    baths: 0,
    area: 535,
    facing: ON_REQUEST,
    furnishing: ON_REQUEST,
    floor: ON_REQUEST,
    parking: 0,
    possession: ON_REQUEST,
    featured: false,
    summary:
      'Premium studio apartments by Happy Group near Club 07, Shela — a corner address with triple-road connectivity, built for rental yield.',
    description: [
      'Codename 9% Club is a set of premium studio (1 RK) apartments by Happy Group, centrally located in West Ahmedabad’s most in-demand micro-market, near Club 07 on the 45 m road, Shela. The 45 m road, 18 m road, Club 07 Road and S.P. Ring Road are all within minutes.',
      'Two efficient layouts: 535 sq.ft. SBA at ₹23,00,000 and 600 sq.ft. SBA at ₹25,78,000. Both totals are basic (₹3,600/sq.ft.) plus AUDA and GEB (₹600/sq.ft.), deposit and running maintenance, and legal fees. Stamp duty and registration (6%) and GST (1%) are extra.',
      'Shela is one of Ahmedabad’s fastest-growing residential hotspots, and studio rental yields here are outperforming standard residential and commercial benchmarks.',
    ],
    highlights: [
      '535 sq.ft. SBA — ₹23.00 L all-in before stamp duty',
      '600 sq.ft. SBA — ₹25.78 L all-in before stamp duty',
      'Rare corner address with triple-road connectivity',
      'Positioned for rental yield',
    ],
    amenities: [
      'Ultra-modern amenities',
      'Corner plot',
      'Triple-road access',
      'Near S.P. Ring Road',
      'Near Club 07',
    ],
    images: gallery('9-percent-club-studios-shela', 11),
  },
  {
    id: 'p9',
    slug: 'happy-skyside-south-bopal',
    title: 'Happy Skyside',
    locality: 'South Bopal',
    city: 'Ahmedabad',
    price: 0,
    rent: null,
    type: 'Apartment',
    status: 'For Sale',
    beds: 2,
    baths: 0,
    area: 0,
    facing: ON_REQUEST,
    furnishing: ON_REQUEST,
    floor: '14-storey towers',
    parking: 0,
    possession: 'August 2026 (per developer)',
    featured: false,
    summary:
      '2 & 3 BHK luxury homes in South Bopal — three 14-floor towers, homes open on three sides, and a private foyer for every home.',
    description: [
      'Happy Skyside offers 2 and 3 BHK luxury homes in South Bopal, Ahmedabad, across three towers of 14 floors each.',
      'Homes are open on three sides and every one has a private foyer. Call us for current pricing and the layouts still available.',
    ],
    highlights: [
      '2 & 3 BHK luxury living',
      '3 towers · 14 floors',
      'Homes open on three sides',
      'Private foyer for every home',
    ],
    amenities: [
      'Club house',
      'Gymnasium',
      'Indoor games',
      'Yoga deck',
      'Children’s play area',
      'Garden & walkway',
      'Senior citizen sitting',
      'CCTV & security cabin',
      'Power backup',
      'Solar panels',
      'High-speed elevators',
      '24x7 water supply',
    ],
    images: gallery('happy-skyside-south-bopal', 9),
  },
]

export const heroImage = new URL('../assets/properties/hero.webp', import.meta.url).href

export const findProperty = (slug: string) =>
  properties.find((p) => p.slug === slug)

/** Two decimals at most, and no trailing zeros — "7.20 Cr" reads wrong. */
const trim = (n: number) =>
  n.toFixed(2).replace(/\.00$/, '').replace(/(\.\d)0$/, '$1')

/** Indian short scale: 47500000 -> "₹4.75 Cr" */
export function formatPrice(rupees: number): string {
  if (rupees >= 10000000) return `₹${trim(rupees / 10000000)} Cr`
  if (rupees >= 100000) return `₹${trim(rupees / 100000)} L`
  return `₹${rupees.toLocaleString('en-IN')}`
}

/** Sale price or monthly rent, whichever this listing actually is. */
export function displayPrice(p: Property): string {
  if (p.rent) return `${formatPrice(p.rent)}/mo`
  if (!p.price) return 'Price on request'
  return `${p.priceFrom ? 'From ' : ''}${formatPrice(p.price)}`
}

/** Rentals have to sort against sale stock somehow — annualise them. */
export function sortValue(p: Property): number {
  return p.rent ? p.rent * 12 : p.price
}

export const cities = [...new Set(properties.map((p) => p.city))].sort()

/** Localities we currently hold stock in — used for the home page ticker. */
export const localities = [...new Set(properties.map((p) => p.locality))]
